#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare notepad3 for snap
#
# Date: Feb 12 2018
#

dlnp3 () {
    ver="$(wget -qO- https://github.com/rizonesoft/Notepad3/releases | grep -m2 -oP 'RELEASE_\K[^"]+' | tail -n1)"
    if wget -q --method=HEAD "https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_${ver}/Notepad3_${ver}.zip"; then
     wget --accept "*.zip" "https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_${ver}/Notepad3_${ver}.zip" &> /dev/null
     unzip Notepad3_${ver}.zip &> /dev/null
    else
     wget --accept "*.zip" "https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_${ver}/Notepad3_${ver}_x64_Portable.zip" &> /dev/null
     wget --accept "*.zip" "https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_${ver}/Notepad3_${ver}_x86_Portable.zip" &> /dev/null
    fi
}

mknp3 () {
    mkdir -p ./{wine-runtime,wine-platform,bin} && mkdir -p sommelier/hooks && mkdir -p usr/share/{pixmaps,applications}
    ARCHITECTURE=$(dpkg --print-architecture)
    if [ "${ARCHITECTURE}" = "amd64" ]; then
     unzip Notepad3_${ver}_x64_Portable.zip -x 'Changes.txt' -x 'License.txt' -x 'Readme.txt' -d "usr/share/notepad3" &> /dev/null
    elif [ "${ARCHITECTURE}" = "i386" ]; then
     unzip Notepad3_${ver}_x86_Portable.zip -x 'Changes.txt' -x 'License.txt' -x 'Readme.txt' -d "usr/share/notepad3" &> /dev/null
    else
     echo "ERROR! Notepad3 only produces software for amd64 and i386. Failing the build here."
     exit 1
    fi
    mv usr/share/notepad3/Notepad3.exe usr/share/notepad3/notepad3.exe
    find "usr" -type d -execdir chmod 755 {} +
}

mkdsk () {
cat > notepad3.desktop <<'EOF1'
[Desktop Entry]
Name=Notepad3
GenericName=Text Editor
Comment=Simple and free source code editor.
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/notepad3.png
Exec=notepad3 %F
StartupWMClass=notepad3.exe
Categories=Utility;TextEditor
MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh;application/x-wine-extension-ini;application/x-wine-extension-inf;
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' notepad3.desktop
}

dlnp3
mknp3
mkdsk
mv pre-install sommelier/hooks && mv notepad3.desktop usr/share/applications && mv notepad3.png usr/share/pixmaps && cp -R -p {sommelier,bin,usr,wine-runtime,wine-platform} $SNAPCRAFT_PART_INSTALL