#!/bin/bash

# notepad3 env
progName=notepad3
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe

if [ ! -d $progHome ];then
ensure_dir_exists $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null

chklnk=$(find $progHome/ -type l -name "*.ini" | wc -l)
if [ $chklnk -ge 1 ]; then
rm "$progHome/minipath.ini"; rm "$progHome/Notepad3.ini"; rm "$progHome/Themes/Dark.ini"; rm "$progHome/Themes/Obsidian.ini" ; rm "$progHome/Themes/Sombra.ini"; find "$progRealPath/" -maxdepth 1 -type f -name "*.ini" -exec cp {} "$progHome/" \; && find "$progRealPath/Themes/" -type f -name "*.ini" 2>/dev/null -exec cp {} "$progHome/Themes/" \;
fi
