#!/bin/bash

# notepad3 env
progName=notepad3
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe

if [ ! -d $progHome ];then
ensure_dir_exists $progHome
fi

# Delete broken symlinks
find "$progHome/" -type l -delete &>/dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &>/dev/null

chklnk=$(find $progHome/ -type l -name "*.ini" | wc -l)
if [ $chklnk -ge 1 ]; then
rm "$progHome/minipath.ini"; rm "$progHome/Notepad3.ini"; rm "$progHome/themes/Dark.ini"; rm "$progHome/themes/Obsidian.ini"; find "$progRealPath/" -maxdepth 1 -type f -name "*.ini" -exec cp {} "$progHome/" \; && find "$progRealPath/themes/" -type f -name "*.ini" 2>/dev/null -exec cp {} "$progHome/themes/" \;
fi

if ! snapctl is-connected "gaming-graphics-core24"; then
msg="Not connected to the gaming-mesa content interface.\n
To connect:\n
 snap connect $SNAP_NAME:gaming-graphics-core24 gaming-graphics-core24 "
  echo "$msg"
  action=$(yad --width 400 --entry --title "${SNAP_NAME}" \
      --center \
      --width=400 \
      --button="Exit:1" \
      --text "$msg" 2>/dev/null)
  ret=$?

  [[ $ret -eq 1 ]] && exit 0

  case $action in
      *) exit 1 ;;    
  esac

  eval $cmd 2>/dev/null
fi
